const javascriptProjects = [
    {
        "id": 2,
        "created_at": "2023-03-27T16:26:28.34362+00:00",
        "title": "Digital Clock",
        "img": "https://i.imgur.com/vScDs74.png",
        "desc": [
            "1. Selects clock elements in HTML with class names '.h', '.m', '.s'",
            "2. Formats hour, minute, and second values.",
            "3. Updates clock element's innerHTML with formatted values.",
            "4. Displays AM/PM based on hour value.",
            "5. Runs the getTime function every second with setInterval."
        ],
        "viewUrl": "https://ravisdraw.github.io/js-projects/02%20Digital%20Clock/index.html",
        "sourceCode": "https://gist.github.com/ravisdraw/bc2662a09b04939a4f5192f868a30acc"
    },
    {
        "id": 8,
        "created_at": "2023-03-28T06:16:50.64343+00:00",
        "title": "Image Slider",
        "img": "https://i.imgur.com/SBz0Md1.png",
        "desc": [
            "1. Retrieve all the image preview elements with class imgPrev a",
            "2. Add a click event listener to each image",
            "3. Get the value of data-list attribute of the clicked image",
            "4. Pass this value to the imageSlider function"
        ],
        "viewUrl": "https://ravisdraw.github.io/js-projects/10%20Image%20Slider/index.html",
        "sourceCode": "https://gist.github.com/ravisdraw/ed4a3560f3495d8b2dd2d4c114ff9793"
    },
    {
        "id": 9,
        "created_at": "2023-03-28T06:17:39.085323+00:00",
        "title": "Sticky Notes",
        "img": "https://i.imgur.com/7SEQoMq.png",
        "desc": [
            "1. Uses local storage to store sticky notes",
            "2. Creates note element with textarea, change, and double-click events",
            "3. Double-click event prompts for note deletion",
            "4. Note content updates on change and saves to local storage",
            "5. Button adds new empty note with unique id, inserted before button"
        ],
        "viewUrl": "https://ravisdraw.github.io/js-projects/06%20Sticky%20Notes/index.html",
        "sourceCode": "https://gist.github.com/ravisdraw/c47ea871d552ddeceec904d03c0c069a"
    },
    {
        "id": 10,
        "created_at": "2023-03-28T06:23:23.768775+00:00",
        "title": "Image Search",
        "img": "https://i.imgur.com/DiiqBot.png",
        "desc": [
            "1. Keyup event listener added to searchBox",
            "2. ImgBox and btns elements selected using querySelectorAll",
            "3. Filter applied to imgBox elements when searchBox changes",
            "4. Display property set to block or none based on searchText",
            "5. Click event listener added to btns, active class removed and added based on target filter"
        ],
        "viewUrl": "https://ravisdraw.github.io/js-projects/09%20Image%20Filter/index.html",
        "sourceCode": "https://gist.github.com/ravisdraw/8a4ad5ed5e491c14e129158b52cd6a1e"
    },
    {
        "id": 3,
        "created_at": "2023-03-28T06:09:17.311646+00:00",
        "title": "Analog Clock",
        "img": "https://i.imgur.com/jYF20ip.png",
        "desc": [
            "1. Selects hour, minute, and second elements from the HTML document using querySelector.",
            "2. Gets the current time using JavaScript's built-in Date object.",
            "3. Calculates the degree of rotation for each hand based on the time.",
            "4. Sets the CSS variable for rotation for each hand using style.setProperty method.",
            "5. Uses setInterval to repeatedly call getTime every second to update the clock."
        ],
        "viewUrl": "https://ravisdraw.github.io/js-projects/03%20Analog%20Clock/index.html",
        "sourceCode": "https://gist.github.com/ravisdraw/ab9a8c790a741683a9e479dee242e2bd"
    },
    {
        "id": 6,
        "created_at": "2023-03-28T06:14:40.228005+00:00",
        "title": "Password Generator",
        "img": "https://i.imgur.com/ZYuduYe.png",
        "desc": [
            "1. Code uses DOM manipulation for input box, form, checkboxes",
            "2. Limit for generated password is set to 8 characters",
            "3. Password is generated by selecting random values from filtered checkbox's function",
            "4. Functions for generating characters are small, large, numbers, and symbols",
            "5. Generated password length can be controlled by max-min characters limit."
        ],
        "viewUrl": "https://ravisdraw.github.io/js-projects/08%20Password%20Generator/index.html",
        "sourceCode": "https://gist.github.com/ravisdraw/d746bc4fc676565fdffebc801071182f"
    },
    {
        "id": 1,
        "created_at": "2023-03-27T16:25:24.997069+00:00",
        "title": "New Year Countdown",
        "img": "https://i.imgur.com/Y0qKfmS.png",
        "desc": [
            "1. DOM selection: Select the HTML elements for displaying the countdown timer.",
            "2. New Year's date: Calculate the date of the next New Year's.",
            "3. Time difference: Calculate the time difference between current time and New Year's.",
            "4. Display update: Continuously update the display with the calculated time until New Year's arrives.",
            "5. Timers: Use JavaScript's setInterval to run the countdown logic every second."
        ],
        "viewUrl": "https://ravisdraw.github.io/js-projects/01%20NewYear%20CountDown/index.html",
        "sourceCode": "https://gist.github.com/ravisdraw/38ec38671c7f138a9d28578029d4f271"
    },
    {
        "id": 4,
        "created_at": "2023-03-28T06:10:24.14684+00:00",
        "title": "Stopwatch",
        "img": "https://i.imgur.com/c5HSpGf.png",
        "desc": [
            "1. Selects start, stop, reset buttons and time elements using querySelector.",
            "2. Initializes variables for hour, minute, second, and millisecond.",
            "3. UpdateValues function formats and displays time.",
            "4. Digits are displayed in HTML elements using innerText.",
            "5. Classes are added/removed to buttons to manage their appearance."
        ],
        "viewUrl": "https://ravisdraw.github.io/js-projects/04%20StopWatch/index.html",
        "sourceCode": "https://gist.github.com/ravisdraw/a754630f8109f544c979feac1f771390"
    }
]

export default javascriptProjects;